In [1]:
from __init__ import * 

/home/pourya/.conda/envs/htv_reg/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
device = 'cpu'
sam = Sampler(device)

In [3]:
x = torch.Tensor([[[[0, 0, 0], [0, 5, 0], [0, 0, 0]]]]).to(device).double()
x_up = sam.upsample(x)
print(x_up)

tensor([[[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 2.5000, 2.5000, 0.0000],
          [0.0000, 2.5000, 5.0000, 2.5000, 0.0000],
          [0.0000, 2.5000, 2.5000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]]]], dtype=torch.float64)


In [4]:
x = torch.Tensor([[[[0, 3, 0], [0, 5, 0], [0, 4, 0]]]]).to(device).double()
print(x)
print(F.pad(x, (0, 1, 0, 1)))

tensor([[[[0., 3., 0.],
          [0., 5., 0.],
          [0., 4., 0.]]]], dtype=torch.float64)
tensor([[[[0., 3., 0., 0.],
          [0., 5., 0., 0.],
          [0., 4., 0., 0.],
          [0., 0., 0., 0.]]]], dtype=torch.float64)


In [5]:
print(sam.downsample(x_up))

tensor([[[[ 0.0000,  1.2500,  1.2500],
          [ 1.2500, 12.5000,  1.2500],
          [ 1.2500,  1.2500,  0.0000]]]], dtype=torch.float64)
