In [1]:
from __init__ import * 

In [2]:
device = 'cpu'
sam = SamplerCPWL(device)

In [3]:
x = torch.Tensor([[[[0, 0, 0], [0, 5, 0], [0, 0, 0]]]]).to(device).double()
print(x)
x_up = sam.upsample(x)
print(x_up)

tensor([[[[0., 0., 0.],
          [0., 5., 0.],
          [0., 0., 0.]]]], dtype=torch.float64)
tensor([[[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 2.5000, 2.5000, 0.0000],
          [0.0000, 2.5000, 5.0000, 2.5000, 0.0000],
          [0.0000, 2.5000, 2.5000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]]]], dtype=torch.float64)


In [4]:
print(sam.downsample(x_up))

tensor([[[[ 0.0000,  1.2500,  1.2500],
          [ 1.2500, 12.5000,  1.2500],
          [ 1.2500,  1.2500,  0.0000]]]], dtype=torch.float64)
